# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.show_db_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.show_db_pushButton.setGeometry(QtCore.QRect(50, 120, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.show_db_pushButton.setFont(font)
        self.show_db_pushButton.setObjectName("show_db_pushButton")
        self.connect_db_label = QtWidgets.QLabel(self.centralwidget)
        self.connect_db_label.setGeometry(QtCore.QRect(50, 340, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.connect_db_label.setFont(font)
        self.connect_db_label.setObjectName("connect_db_label")
        self.db_list_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.db_list_comboBox.setGeometry(QtCore.QRect(350, 350, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.db_list_comboBox.setFont(font)
        self.db_list_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.db_list_comboBox.setObjectName("db_list_comboBox")
        self.reset_db_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.reset_db_pushButton.setGeometry(QtCore.QRect(310, 440, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reset_db_pushButton.setFont(font)
        self.reset_db_pushButton.setObjectName("reset_db_pushButton")
        self.next_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.next_pushButton.setGeometry(QtCore.QRect(560, 440, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.next_pushButton.setFont(font)
        self.next_pushButton.setObjectName("next_pushButton")
        self.back_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.back_pushButton.setGeometry(QtCore.QRect(60, 440, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back_pushButton.setFont(font)
        self.back_pushButton.setObjectName("back_pushButton")
        self.show_db_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.show_db_textBrowser.setGeometry(QtCore.QRect(350, 60, 291, 251))
        self.show_db_textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.show_db_textBrowser.setObjectName("show_db_textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MySQL-Database Information"))
        self.show_db_pushButton.setText(_translate("MainWindow", "Show Databases"))
        self.connect_db_label.setText(_translate("MainWindow", "Connect to Database"))
        self.reset_db_pushButton.setStatusTip(_translate("MainWindow", "Reset all fields"))
        self.reset_db_pushButton.setText(_translate("MainWindow", "Reset"))
        self.next_pushButton.setStatusTip(_translate("MainWindow", "See table information"))
        self.next_pushButton.setText(_translate("MainWindow", "Next >>"))
        self.back_pushButton.setStatusTip(_translate("MainWindow", "Go back to login page"))
        self.back_pushButton.setText(_translate("MainWindow", "<< Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
