# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mysql_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mysql_Window(object):
    def setupUi(self, Mysql_Window):
        Mysql_Window.setObjectName("Mysql_Window")
        Mysql_Window.resize(746, 462)
        Mysql_Window.setStyleSheet("background-color: rgb(88, 197, 255);")
        self.centralwidget = QtWidgets.QWidget(Mysql_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.u_name_label = QtWidgets.QLabel(self.centralwidget)
        self.u_name_label.setGeometry(QtCore.QRect(110, 70, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.u_name_label.setFont(font)
        self.u_name_label.setObjectName("u_name_label")
        self.pswd_label = QtWidgets.QLabel(self.centralwidget)
        self.pswd_label.setGeometry(QtCore.QRect(110, 110, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pswd_label.setFont(font)
        self.pswd_label.setObjectName("pswd_label")
        self.h_name_label = QtWidgets.QLabel(self.centralwidget)
        self.h_name_label.setGeometry(QtCore.QRect(110, 150, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.h_name_label.setFont(font)
        self.h_name_label.setObjectName("h_name_label")
        self.port_label = QtWidgets.QLabel(self.centralwidget)
        self.port_label.setGeometry(QtCore.QRect(110, 190, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.port_label.setFont(font)
        self.port_label.setObjectName("port_label")
        self.uname_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.uname_lineEdit.setGeometry(QtCore.QRect(280, 70, 201, 20))
        self.uname_lineEdit.setObjectName("uname_lineEdit")
        self.paswd_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.paswd_lineEdit.setGeometry(QtCore.QRect(280, 110, 201, 20))
        self.paswd_lineEdit.setObjectName("paswd_lineEdit")
        self.hname_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.hname_lineEdit.setGeometry(QtCore.QRect(280, 150, 201, 20))
        self.hname_lineEdit.setObjectName("hname_lineEdit")
        self.port_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.port_lineEdit.setGeometry(QtCore.QRect(280, 190, 201, 20))
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.check_con_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.check_con_pushButton.setGeometry(QtCore.QRect(60, 250, 161, 23))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.check_con_pushButton.setFont(font)
        self.check_con_pushButton.setObjectName("check_con_pushButton")
        self.login_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.login_pushButton.setGeometry(QtCore.QRect(480, 250, 161, 23))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.login_pushButton.setFont(font)
        self.login_pushButton.setObjectName("login_pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.reset_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.reset_pushbutton.setGeometry(QtCore.QRect(270, 250, 161, 23))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.reset_pushbutton.setFont(font)
        self.reset_pushbutton.setObjectName("reset_pushbutton")
        Mysql_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mysql_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 746, 20))
        self.menubar.setObjectName("menubar")
        Mysql_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Mysql_Window)
        self.statusbar.setObjectName("statusbar")
        Mysql_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Mysql_Window)
        QtCore.QMetaObject.connectSlotsByName(Mysql_Window)

    def retranslateUi(self, Mysql_Window):
        _translate = QtCore.QCoreApplication.translate
        Mysql_Window.setWindowTitle(_translate("Mysql_Window", "MySQL Log In"))
        self.u_name_label.setText(_translate("Mysql_Window", "USER NAME"))
        self.pswd_label.setText(_translate("Mysql_Window", "PASSWORD"))
        self.h_name_label.setText(_translate("Mysql_Window", "HOST NAME"))
        self.port_label.setText(_translate("Mysql_Window", "PORT"))
        self.check_con_pushButton.setText(_translate("Mysql_Window", "Check Connectivity"))
        self.login_pushButton.setText(_translate("Mysql_Window", "Log In"))
        self.label_2.setText(_translate("Mysql_Window", "MySQL Log In"))
        self.reset_pushbutton.setText(_translate("Mysql_Window", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mysql_Window = QtWidgets.QMainWindow()
    ui = Ui_Mysql_Window()
    ui.setupUi(Mysql_Window)
    Mysql_Window.show()
    sys.exit(app.exec_())
