# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_info_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Table_Info_MainWindow(object):
    def setupUi(self, Table_Info_MainWindow):
        Table_Info_MainWindow.setObjectName("Table_Info_MainWindow")
        Table_Info_MainWindow.resize(800, 600)
        Table_Info_MainWindow.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.centralwidget = QtWidgets.QWidget(Table_Info_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.show_count_in_table_info_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.show_count_in_table_info_pushButton.setGeometry(QtCore.QRect(60, 30, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.show_count_in_table_info_pushButton.setFont(font)
        self.show_count_in_table_info_pushButton.setObjectName("show_count_in_table_info_pushButton")
        self.show_count_in_table_info_label = QtWidgets.QLabel(self.centralwidget)
        self.show_count_in_table_info_label.setGeometry(QtCore.QRect(560, 30, 181, 31))
        self.show_count_in_table_info_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.show_count_in_table_info_label.setText("")
        self.show_count_in_table_info_label.setObjectName("show_count_in_table_info_label")
        self.desc_table_in_table_info_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.desc_table_in_table_info_pushButton.setGeometry(QtCore.QRect(60, 130, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.desc_table_in_table_info_pushButton.setFont(font)
        self.desc_table_in_table_info_pushButton.setObjectName("desc_table_in_table_info_pushButton")
        self.back_in_table_info_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.back_in_table_info_pushButton.setGeometry(QtCore.QRect(30, 480, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back_in_table_info_pushButton.setFont(font)
        self.back_in_table_info_pushButton.setObjectName("back_in_table_info_pushButton")
        self.reset_in_table_info_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.reset_in_table_info_pushButton.setGeometry(QtCore.QRect(270, 480, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reset_in_table_info_pushButton.setFont(font)
        self.reset_in_table_info_pushButton.setObjectName("reset_in_table_info_pushButton")
        self.next_in_table_info_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.next_in_table_info_pushButton.setGeometry(QtCore.QRect(530, 480, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.next_in_table_info_pushButton.setFont(font)
        self.next_in_table_info_pushButton.setObjectName("next_in_table_info_pushButton")
        self.show_tname_in_table_info_label = QtWidgets.QLabel(self.centralwidget)
        self.show_tname_in_table_info_label.setGeometry(QtCore.QRect(320, 30, 181, 31))
        self.show_tname_in_table_info_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.show_tname_in_table_info_label.setText("")
        self.show_tname_in_table_info_label.setObjectName("show_tname_in_table_info_label")
        self.filter_cond_in_table_info_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.filter_cond_in_table_info_lineEdit.setGeometry(QtCore.QRect(280, 340, 481, 20))
        self.filter_cond_in_table_info_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filter_cond_in_table_info_lineEdit.setObjectName("filter_cond_in_table_info_lineEdit")
        self.filter_cond_in_table_info_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.filter_cond_in_table_info_pushButton.setGeometry(QtCore.QRect(60, 330, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.filter_cond_in_table_info_pushButton.setFont(font)
        self.filter_cond_in_table_info_pushButton.setObjectName("filter_cond_in_table_info_pushButton")
        self.desc_table_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.desc_table_tableWidget.setGeometry(QtCore.QRect(290, 90, 471, 192))
        self.desc_table_tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.desc_table_tableWidget.setObjectName("desc_table_tableWidget")
        self.desc_table_tableWidget.setColumnCount(0)
        self.desc_table_tableWidget.setRowCount(0)
        Table_Info_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Table_Info_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        Table_Info_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Table_Info_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Table_Info_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Table_Info_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Table_Info_MainWindow)

    def retranslateUi(self, Table_Info_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Table_Info_MainWindow.setWindowTitle(_translate("Table_Info_MainWindow", "MySQL-Table Info Information"))
        self.show_count_in_table_info_pushButton.setText(_translate("Table_Info_MainWindow", "Show Record Count"))
        self.desc_table_in_table_info_pushButton.setText(_translate("Table_Info_MainWindow", "DESC Table"))
        self.back_in_table_info_pushButton.setStatusTip(_translate("Table_Info_MainWindow", "Go back to table page"))
        self.back_in_table_info_pushButton.setText(_translate("Table_Info_MainWindow", "<< Back"))
        self.reset_in_table_info_pushButton.setStatusTip(_translate("Table_Info_MainWindow", "Reset all fields"))
        self.reset_in_table_info_pushButton.setText(_translate("Table_Info_MainWindow", "Reset"))
        self.next_in_table_info_pushButton.setStatusTip(_translate("Table_Info_MainWindow", "More info on table (record-wise)"))
        self.next_in_table_info_pushButton.setText(_translate("Table_Info_MainWindow", "Next >>"))
        self.filter_cond_in_table_info_pushButton.setText(_translate("Table_Info_MainWindow", "Filter Condition"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Table_Info_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Table_Info_MainWindow()
    ui.setupUi(Table_Info_MainWindow)
    Table_Info_MainWindow.show()
    sys.exit(app.exec_())
