# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Table_MainWindow(object):
    def setupUi(self, Table_MainWindow):
        Table_MainWindow.setObjectName("Table_MainWindow")
        Table_MainWindow.resize(807, 490)
        Table_MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Table_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.show_in_table_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.show_in_table_pushButton.setGeometry(QtCore.QRect(70, 50, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.show_in_table_pushButton.setFont(font)
        self.show_in_table_pushButton.setObjectName("show_in_table_pushButton")
        self.show_in_table_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.show_in_table_textBrowser.setGeometry(QtCore.QRect(390, 30, 256, 192))
        self.show_in_table_textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.show_in_table_textBrowser.setObjectName("show_in_table_textBrowser")
        self.connect_in_table__label = QtWidgets.QLabel(self.centralwidget)
        self.connect_in_table__label.setGeometry(QtCore.QRect(80, 280, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.connect_in_table__label.setFont(font)
        self.connect_in_table__label.setObjectName("connect_in_table__label")
        self.table_list_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.table_list_comboBox.setGeometry(QtCore.QRect(390, 290, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.table_list_comboBox.setFont(font)
        self.table_list_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_list_comboBox.setObjectName("table_list_comboBox")
        self.back_in_table_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.back_in_table_pushButton.setGeometry(QtCore.QRect(90, 390, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back_in_table_pushButton.setFont(font)
        self.back_in_table_pushButton.setObjectName("back_in_table_pushButton")
        self.reset_in_table_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.reset_in_table_pushButton.setGeometry(QtCore.QRect(340, 390, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reset_in_table_pushButton.setFont(font)
        self.reset_in_table_pushButton.setObjectName("reset_in_table_pushButton")
        self.next_in_tablepage_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.next_in_tablepage_pushButton.setGeometry(QtCore.QRect(590, 390, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.next_in_tablepage_pushButton.setFont(font)
        self.next_in_tablepage_pushButton.setObjectName("next_in_tablepage_pushButton")
        Table_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Table_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 20))
        self.menubar.setObjectName("menubar")
        Table_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Table_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Table_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Table_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Table_MainWindow)

    def retranslateUi(self, Table_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Table_MainWindow.setWindowTitle(_translate("Table_MainWindow", "MySQL-Table Information"))
        self.show_in_table_pushButton.setText(_translate("Table_MainWindow", "Show Tables"))
        self.connect_in_table__label.setText(_translate("Table_MainWindow", "Retrieve data from"))
        self.back_in_table_pushButton.setStatusTip(_translate("Table_MainWindow", "Go back to database page"))
        self.back_in_table_pushButton.setText(_translate("Table_MainWindow", "<< Back"))
        self.reset_in_table_pushButton.setStatusTip(_translate("Table_MainWindow", "Reset all fields"))
        self.reset_in_table_pushButton.setText(_translate("Table_MainWindow", "Reset"))
        self.next_in_tablepage_pushButton.setStatusTip(_translate("Table_MainWindow", "More info on table"))
        self.next_in_tablepage_pushButton.setText(_translate("Table_MainWindow", "Next >>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Table_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Table_MainWindow()
    ui.setupUi(Table_MainWindow)
    Table_MainWindow.show()
    sys.exit(app.exec_())
